### ISSUE TITLE
hostnames on aws do not work?

### ISSUE THREAD

**Issue by grypyrg** [jayjanssen/vagrant-percona#13]
I see that hostnames are not configured when using --provider=aws?

Others have this too? (with other Vagrantfiles possibly)?

Kenn

**Comment by jayjanssen** [comment]
I don't think aws ever properly set the hostnames on the nodes themselves.
However, hostmanager should work.  Note I have a hacked hostmanager in my
github that caches ip address lookups for nodes that is nice.

On Wed, Jan 14, 2015 at 6:15 AM, Kenny Gryp <notifications@github.com>
wrote:

> I see that hostnames are not configured when using --provider=aws?
>
> Others have this too? (with other Vagrantfiles possibly)?
>
> Kenn
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/jayjanssen/vagrant-percona/issues/13>.
>



-- 
Jay Janssen
Managing Consultant, Percona
https://about.me/jay.janssen

**Comment by jayjanssen** [comment]
Commit fc121a5b65685aedd1b62d850ffcfbc0b3c94ea7 may address this problem to your satisfaction?
